DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS T_MAINTAINER;

CREATE TABLE TASK (

    ID integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	Title CHAR(50) NOT NULL,
	Description TEXT,
	Priority CHAR(1) NOT NULL,
    Done BIT DEFAULT 0,
    CONSTRAINT CHK_Pri CHECK (Priority=='L' OR Priority=='M' OR Priority=='H')
);

CREATE TABLE T_MAINTAINER (
	T_ID INT NOT NULL,
	Maintainer CHAR(50) NOT NULL,
    PRIMARY KEY (T_ID,Maintainer),
    FOREIGN KEY (T_ID)
        REFERENCES TASK(ID)
        ON UPDATE CASCADE
);